# The goal of this workflow is to check if examples run without any errors
name: Run examples
env:
  DEBUG: napi:*
  APP_NAME: scylladb-javascript-driver
  PEDANTIC: true
"on":
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - '**'
jobs:
  build-and-run-examples:
    strategy:
      fail-fast: false
      matrix:
        host:
        - ubuntu-latest
        - ubuntu-24.04-arm
        node: [ 20, current ]
        include:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: npm run build -- --target x86_64-unknown-linux-gnu
          - host: ubuntu-24.04-arm 
            target: aarch64-unknown-linux-gnu 
            build: npm run build -- --target aarch64-unknown-linux-gnu
        exclude:
          - host: ubuntu-24.04-arm
            node: 20
    name: Build and run examples - ${{ matrix.target }} - node@${{ matrix.node }}
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/common/setup
        with:
          host: ${{ matrix.host }}
          target: ${{ matrix.target }}
          node-version: ${{ matrix.node }}
      - uses: ./.github/common/example
        with:
          build-command: ${{ matrix.build }}
