
name: Extended CI
env:
  DEBUG: napi:*
  PEDANTIC: true

on:
  push:
    # Currently we create tags, before triggering a release. 
    # This setup ensures, that we run this workflow, before the release.
    tags:
      - "*"  
  workflow_dispatch:
    
jobs:
  # The goal of this workflow is to check if examples run without any errors
  # This is a version that tests the full matrix of supported node versions and driver architectures
  extended-examples-test:
    strategy:
      fail-fast: false
      matrix:
        host:
        - ubuntu-latest
        - ubuntu-24.04-arm
        node: [ 20, 22, 24, current ]
        include:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: npm run build -- --target x86_64-unknown-linux-gnu
          - host: ubuntu-24.04-arm 
            target: aarch64-unknown-linux-gnu 
            build: npm run build -- --target aarch64-unknown-linux-gnu
    name: Build and run examples - ${{ matrix.target }} - node@${{ matrix.node }}
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/common/setup
        with:
          host: ${{ matrix.host }}
          target: ${{ matrix.target }}
          node-version: ${{ matrix.node }}
      - uses: ./.github/common/example
        with:
          build-command: ${{ matrix.build }}
  extended-integration-tests:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: npm run build -- --target x86_64-unknown-linux-gnu
        node: [ 20, 22, 24, current ]
    name: Build and run integration tests - ${{ matrix.settings.target }} - node@${{ matrix.node }}
    runs-on: ${{ matrix.settings.host }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/common/setup
        with:
          host: ${{ matrix.settings.host }}
          target: ${{ matrix.settings.target }}
          node-version: ${{ matrix.node }}
      - uses: ./.github/common/integration
        with:
          build-command: ${{ matrix.settings.build }}
